stages:         
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - cd individual-frontend
    - npm install
    - npm build
    - echo "BUILD SUCCESSFUL"

test-job:   
  image: node:latest
  stage: test
  before_script:
    - cd individual-frontend
    - npm install
  script:
    - cd individual-frontend
    - npm run test:ci


deploy-job:      
  stage: deploy  
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
