version: '3.8'

services:
  front-end:
    image: simonegeurtz/front-end:latest
    container_name: front-end
    ports:
      - "3000:3000"
    networks:
      - app_network

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: "Y"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app_network
   

  comment-service:
    image: simonegeurtz/comment-service:latest
    ports:
      - "7123:9002"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 40s
        max_attempts: 3
        window: 120s
    environment:
      - ASPNETCORE_URLS=http://+:9002
      - ConnectionStrings__UserConn="Server=34.91.9.181;Database=commentdbNEWSimone;User Id=sqlserver;Password=ok5wje34bdyc;Encrypt=False;"
      - RabbitMq__hostname=rabbitmq
      - RabbitMq__port=5672
      - RabbitMq__username=guest
      - RabbitMq__password=guest
    depends_on:
      - rabbitmq
      - sql-server-db
    command: sh -c dotnet ef database update
    networks:
      - app_network
    

  post-service:
    image: simonegeurtz/post-service:latest
    ports:
      - "7122:9001"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 40s
        max_attempts: 3
        window: 120s
    environment:
      - ASPNETCORE_URLS=http://+:9001
      - ConnectionStrings__UserConn="Server=34.91.9.181;Database=postdbNEWSimone;User Id=sqlserver;Password=ok5wje34bdyc;Encrypt=False;";
      - RabbitMq__hostname=rabbitmq
      - RabbitMq__port=5672
      - RabbitMq__username=guest
      - RabbitMq__password=guest
    depends_on:
      - rabbitmq
      - sql-server-db
    command: sh -c dotnet ef database update
    networks:
      - app_network

  gateway:
    image: simonegeurtz/gateway:latest
    ports:
      - "5003:9003"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 40s
        max_attempts: 3
        window: 120s
    depends_on:
      - post-service
      - comment-service
    command: sh -c dotnet ef database update
    networks:
      - app_network
    
networks:
  app_network:
    driver: bridge

  