version: '3.7'

services:

  individual-project-frontend:
    container_name: individual-project-frontend
    build: ./individual-project-frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start